In [84]:
import numpy as np
import pandas as pd

In [85]:
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [86]:
pd.options.display.max_columns=None

In [87]:
from warnings import filterwarnings
filterwarnings('ignore')

In [88]:
import re

In [89]:
df=pd.read_csv('C:/Users/Sushree Jena/Desktop/imarticus/Tableau/extra_work/netflix/netflix_titles.csv')
df.shape

(8807, 12)

In [90]:
df.head()

show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1      s2  TV Show          Blood & Water              NaN   
2      s3  TV Show              Ganglands  Julien Leclercq   
3      s4  TV Show  Jailbirds New Orleans              NaN   
4      s5  TV Show           Kota Factory              NaN   

                                                cast        country  \
0                                                NaN  United States   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                NaN            NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min   
1  September 24, 2021          2021  TV-MA  2 Seasons   
2  September 24, 2021          2021  TV-MA   1 Season   
3  September 24, 2021          2021  TV-MA   1 Season   
4  September 24, 2021          2021  TV-MA  2 Seasons   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64 
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB


In [92]:
#Converting the show id column into an integer column by splitting it and extracting the numeric part

In [93]:
def str_split(x):
    return re.findall('(\d+|[A-Za-z_]+)',x)

In [94]:
df['show_id']=df.show_id.apply(lambda x:str_split(x)).apply(lambda x:int(x[-1]))

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       8807 non-null   int64 
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64 
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(2), object(10)
memory usage: 825.8+ KB


In [96]:
selected_features=['type','title','director','country','rating','duration','listed_in','description']

In [98]:
for i in selected_features :
    df[i]=df[i].fillna('')

In [99]:
#Combining all the features

In [100]:
combined_features=df['type']+' '+df['title']+' '+df['director']+' '+df['country']+' '+df['rating']+' '+df['duration']+' '+df['listed_in']+' '+df['description']

In [101]:
combined_features[0]

'Movie Dick Johnson Is Dead Kirsten Johnson United States PG-13 90 min Documentaries As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'

In [102]:
#Converting text data into feature vectors

In [103]:
vectorizer=TfidfVectorizer()

In [104]:
feature_vectors=vectorizer.fit_transform(combined_features)

In [105]:
print(feature_vectors)

  (0, 12089)	0.22582262972496134
  (0, 8596)	0.13331724225379857
  (0, 3473)	0.13951333754337386
  (0, 24721)	0.10909124220087824
  (0, 11127)	0.11016092882964895
  (0, 24969)	0.03934508965109414
  (0, 26700)	0.1518175653403859
  (0, 5262)	0.20840117793456034
  (0, 1382)	0.038813320708976556
  (0, 12390)	0.20840117793456034
  (0, 11974)	0.045719774508762086
  (0, 6349)	0.11928213820638427
  (0, 23406)	0.18710532729729584
  (0, 8999)	0.15364628746244383
  (0, 14328)	0.0826046833831589
  (0, 11313)	0.11329256718870442
  (0, 17421)	0.04205802540145196
  (0, 8007)	0.14458700955549095
  (0, 24706)	0.0688666280849842
  (0, 16837)	0.20452677908769684
  (0, 8777)	0.10845490841260452
  (0, 11164)	0.06924319023075827
  (0, 1838)	0.0760212646715108
  (0, 7206)	0.0832590252270164
  (0, 15935)	0.03422760130382063
  :	:
  (8806, 8609)	0.2161313358160435
  (8806, 528)	0.13522426727992584
  (8806, 3525)	0.1552592529620318
  (8806, 26860)	0.13409536008994025
  (8806, 21)	0.18919151533140782
  (8806, 16

In [106]:
#Cosine Similarity

In [107]:
#Getting the similarity score using cosine similarity

In [108]:
similarity=cosine_similarity(feature_vectors)

In [109]:
print(similarity)

[[1.         0.01556203 0.02347499 ... 0.01660148 0.02619698 0.03505715]
 [0.01556203 1.         0.06253714 ... 0.00242094 0.         0.01483654]
 [0.02347499 0.06253714 1.         ... 0.00963996 0.01861952 0.06936987]
 ...
 [0.01660148 0.00242094 0.00963996 ... 1.         0.06232514 0.01180387]
 [0.02619698 0.         0.01861952 ... 0.06232514 1.         0.01938709]
 [0.03505715 0.01483654 0.06936987 ... 0.01180387 0.01938709 1.        ]]


In [110]:
print(similarity.shape)

(8807, 8807)


In [111]:
#Getting a movie name from user

In [141]:
name=input('Enter your favorite movie or TV show name: ')

Enter your favorite movie or TV show name: Ganglands


In [142]:
#Creating a list with all the titles in the dataset

In [143]:
list_of_all_titles=df['title'].to_list()

In [144]:
print(list_of_all_titles)

['Dick Johnson Is Dead', 'Blood & Water', 'Ganglands', 'Jailbirds New Orleans', 'Kota Factory', 'Midnight Mass', 'My Little Pony: A New Generation', 'Sankofa', 'The Great British Baking Show', 'The Starling', 'Vendetta: Truth, Lies and The Mafia', 'Bangkok Breaking', 'Je Suis Karl', 'Confessions of an Invisible Girl', 'Crime Stories: India Detectives', 'Dear White People', "Europe's Most Dangerous Man: Otto Skorzeny in Spain", 'Falsa identidad', 'Intrusion', 'Jaguar', 'Monsters Inside: The 24 Faces of Billy Milligan', 'Resurrection: Ertugrul', 'Avvai Shanmughi', 'Go! Go! Cory Carson: Chrissy Takes the Wheel', 'Jeans', 'Love on the Spectrum', 'Minsara Kanavu', 'Grown Ups', 'Dark Skies', 'Paranoia', 'Ankahi Kahaniya', 'Chicago Party Aunt', 'Sex Education', 'Squid Game', 'Tayo and Little Wizards', 'The Father Who Moves Mountains', 'The Stronghold', 'Angry Birds', 'Birth of the Dragon', 'Chhota Bheem', 'He-Man and the Masters of the Universe', 'Jaws', 'Jaws 2', 'Jaws 3', 'Jaws: The Revenge

In [145]:
#Finding close match for movie name entered by the user

In [146]:
find_close_match=difflib.get_close_matches(name,list_of_all_titles)

In [147]:
print(find_close_match)

['Ganglands', 'Strongland', 'Hangman']


In [148]:
#finding the closest match

In [149]:
close_match=find_close_match[0]

In [150]:
print(close_match)

Ganglands


In [151]:
#finding the index of the movie with title

In [152]:
index_of_the_show=df[df.title==close_match]['show_id'].values[0]
print(index_of_the_show)

3


In [153]:
#getting a list of similar shows

In [154]:
similarity_score=list(enumerate(similarity[index_of_the_show]))
print(similarity_score)

[(0, 0.008905087909488648), (1, 0.04621504392689403), (2, 0.03481720492889752), (3, 1.0000000000000002), (4, 0.030208230011816096), (5, 0.03356474133319267), (6, 0.020140035969003437), (7, 0.022547655504053653), (8, 0.06313468946047049), (9, 0.005249716412566685), (10, 0.05816626951165093), (11, 0.03500645043602427), (12, 0.012305999748725002), (13, 0.06131540170799778), (14, 0.0544350655657194), (15, 0.037069278270174096), (16, 0.010463474828969501), (17, 0.033359431971180416), (18, 0.04659149343390967), (19, 0.06698433774656866), (20, 0.04091974584089925), (21, 0.042679331334617016), (22, 0.007786935487407222), (23, 0.04270673594731854), (24, 0.009175525293795088), (25, 0.08207746031124029), (26, 0.008595665484578746), (27, 0.01756111094445499), (28, 0.005285039478426123), (29, 0.011842655772531085), (30, 0.00860817680122038), (31, 0.022813120287273714), (32, 0.024990577156898064), (33, 0.034978972959589676), (34, 0.02558627983238845), (35, 0.02708769979564082), (36, 0.01195483861378

In [155]:
len(similarity_score)

8807

In [156]:
#sorting the movies based on the similarity score

In [157]:
sorted_similar_shows=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_shows)

[(3, 1.0000000000000002), (3837, 0.28391726002624434), (4709, 0.2135412162156824), (1465, 0.19334927329547819), (8464, 0.1784435236617027), (1391, 0.17763029760993002), (8495, 0.175533269520959), (2132, 0.17548426351487265), (6360, 0.160558381561059), (8466, 0.1531892982243635), (7474, 0.1451260316482839), (2345, 0.14176584096721825), (957, 0.13966366651084744), (8755, 0.1389219320306869), (8249, 0.13721942654411937), (3721, 0.13590531978267972), (7867, 0.13539612783205723), (2394, 0.13457220881459303), (4807, 0.13046363882271136), (2422, 0.1301203943514775), (1400, 0.12870974497456295), (4408, 0.12787293017783685), (1692, 0.12507715848897266), (1688, 0.12406781778370207), (526, 0.12166878612052148), (5262, 0.12125831901607802), (466, 0.11909533746872425), (647, 0.11734122331889119), (2922, 0.11638412747718761), (1697, 0.11636927238451288), (3363, 0.11633994324564219), (431, 0.11531089515170412), (1146, 0.11385292778623696), (184, 0.11384918937318514), (3053, 0.1137680840830392), (6378

In [158]:
#getting the names of the shows based on the index

In [159]:
print('Recommended shows for you are: \n')

i=1

for show in sorted_similar_shows:
    index=show[0]
    title_from_index=df[df.index==index]['title'].values[0]
    if(i<20):
        print(i,'.',title_from_index)
        i+=1

Recommended shows for you are: 

1 . Jailbirds New Orleans
2 . Jailbirds
3 . The Originals
4 . The Haunted Hathaways
5 . The Prince
6 . Cut Throat City
7 . The Runner
8 . Project Power
9 . Border Patrol
10 . The Princess and the Frog
11 . Mississippi Grind
12 . Eric Andre: Legalize Everything
13 . Pet Stars
14 . Women Behind Bars
15 . The Cincinnati Kid
16 . Girls Incarcerated
17 . Rica, Famosa, Latina
18 . Dating Around
19 . Churchill’s Secret Agents: The New Recruits


We will collate all the required steps from above to design our Movie Recommendation system

In [160]:
#Movie Recommendation System

In [161]:
name=input('Enter your favorite movie or TV show name: ')

list_of_all_titles=df['title'].to_list()

find_close_match=difflib.get_close_matches(name,list_of_all_titles)

close_match=find_close_match[0]

index_of_the_show=df[df.title==close_match]['show_id'].values[0]

similarity_score=list(enumerate(similarity[index_of_the_show]))

sorted_similar_shows=sorted(similarity_score,key=lambda x:x[1],reverse=True)

print('Recommended shows for you are: \n')

i=1

for show in sorted_similar_shows:
    index=show[0]
    title_from_index=df[df.index==index]['title'].values[0]
    if(i<6):
        print(i,'.',title_from_index)
        i+=1

Enter your favorite movie or TV show name: kota factory
Recommended shows for you are: 

1 . Midnight Mass
2 . We Are the Wave
3 . Save Me
4 . Evil
5 . The Guest
